# Generated by Django 5.2.1 on 2025-05-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_order_payment_complete_tablebooking_payment_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='for_table_booking',
            field=models.BooleanField(default=False, help_text='Indicates if this order is for a table booking'),
        ),
    ]
