# Generated by Django 5.2.1 on 2025-05-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_alter_otp_code_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
